### PR TITLE
Add filter to view all reviews

### PR DESCRIPTION
**Pull request by anevins12**
An option will appear on the first Reviews page of a plugin or theme that will toggle all reviews on the same page. This is to help find duplicate IPs easier.

### CODE REVIEW

**Comment by keesiemeijer** [comment]
Hi anevins.

Looks good but there are some changes I like to see.

Could the button go under the ratings and the total reviews made visible again. 
Also make the button visible on paginated pages. Why hide such a useful button.
The hide button text is a bit confusing when on the `/?filter=#` pages (e.g. "hide 10 reviews" from a total of 25? ). Maybe just use "show # reviews" and hide/disable the button after clicking.

If you need to add styles to the button you can add it like this in `reviews_init()`
```javascript
// your styles for the button (example selector)
styles += ' button{ margin-top: 1em; }'

// styles already in reviews_init()
$( "head" ).append( '<style type=\"text/css\">' + styles + '</style>' );
```

**Comment by anevins12** [comment]
Hi Keesiemeijer,
I can do all of that, but this point:
"Also make the button visible on paginated pages"
- I thought of doing this but I would I thought it would have been too complicated to write. Also, I don't think it's necessary to be on all pages; if a moderator is using the pagination then I would say they don't want to view all of the reviews. If a moderator is not using the pagination then they might want to view all the reviews.

**Comment by keesiemeijer** [comment]
You never know how you arrive at a page. It's just a nice option to have if you need it.
You can have it on all pages by replacing this line
```javascript
if (pagination.children().first().hasClass('current')) {
```
with this
```javascript
if ( obj_exists( pagination ) ) {
```
I'll leave it up to you to if you want to add it on all pages or not.

**Comment by keesiemeijer** [comment]
Aha, I see now you would have to get the reviews from previous pages as well on the paginated pages. Hiding the button on paginated pages is best I think.

**Comment by anevins12** [comment]
No worries, I should get some more free time soon. By the way, I found an issue because I was running the duplicate IPs script again. If the "Duplicate IP" text was already on the page, and I ran the duplicate_ips script again, the text itself would duplicate - if you know what I mean ;) So you'd see "Duplicate IP Duplicate IP".

**Comment by keesiemeijer** [comment]
Good to hear.

Add ` $('.wpmt_ip-warning').remove();` add the top of the `check_duplicate_IPs()` function.
Don't worry about the styling of the warning. I'm working on better duplicate IP detection and the styles for the warning will change.

**Comment by anevins12** [comment]
I'm trying to add some styles:
{code}
			// Add some CSS
			styles += '.reviews-toggle-all { margin-bottom: 2em; }';
{code}
But it doesn't seem to be applying at all.

**Comment by keesiemeijer** [comment]
Are you adding it before the styles get added to the DOM in `reviews_init()`.

**Comment by anevins12** [comment]
Yes :P
```


		$( "head" ).append( '<style type=\"text/css\">' + styles + '</style>' );

		// test if duplicate IPs are found

		// var ip1 = next_prev_objects.eq( 0 ).find( '.post-ip-link' ).text();
		// if ( obj_exists( next_prev_objects.eq( 1 ) ) ) {
		// next_prev_objects.eq( 1 ).find( '.post-ip-link' ).text( ip1 );
		// }

		check_duplicate_IPs();
		
    		viewAllReviews();
```
Do you think I could just move this line
```

		$( "head" ).append( '<style type=\"text/css\">' + styles + '</style>' );
```
Below this line:
```
    		viewAllReviews();
```

**Comment by keesiemeijer** [comment]
I think so. Try it.

**Comment by anevins12** [comment]
Okay I've updated the code to your recommendations. There's still the small problem with the wording of the button when it shows less. I want to have the functionality to show less reviews because sometimes there can be hundreds and hundreds on the page (or thousands), but the wording is difficult to achieve. I have it at "Show less reviews" and I've also added a little plus and minus icon to help this labelling.

**Comment by keesiemeijer** [comment]
That's a difficult one. Maybe just "less reviews" with the minus icon?

**Comment by anevins12** [comment]
Okie dokie I've updated the button text again. It's now "All reviews +" and "Fewer reviews -". As I've taken away the "hide" and "show" text, I added some ARIA to substitute some of that association.

**Comment by anevins12** [comment]
Didn't meant to close lol

**Comment by anevins12** [comment]
Here are a few test cases 

	1. https://wordpress.org/support/view/plugin-reviews/social-networks-auto-poster-facebook-twitter-g
	2. https://wordpress.org/support/view/plugin-reviews/slider-image
	3. https://wordpress.org/support/view/plugin-reviews/portfolio-gallery

**Comment by keesiemeijer** [comment]
Thanks anevins12

I will add the code to the minified versions and update the add-on on of these days

**Pull request merged**
