### PR TITLE
Add button to strip links in editor

### PR DESCRIPTION
**Pull request by anevins12**
Though - I want to do this for only the editor when you edit a Review, because the button is kind of redundant otherwise. I just can't figure out a way to do that.

Test: https://wordpress.org/support/edit.php?id=6772875

### CODE REVIEW

**Comment by keesiemeijer** [comment]
It strips the links in the DOM but not visibly in the textarea text if you edited the post manually before you clicked the button.

Change this
```javascript
post.html( updatedContent );
```
to this
```
post.val( updatedContent );
```

**Comment by anevins12** [comment]
Cool, will look into it.

It also seems to struggle to strip out 'http' links in some cases, needs more investigating

**Comment by anevins12** [comment]
Fixed that.

**Comment by anevins12** [comment]
Should be ready for review now.

**Pull request merged**
